# docker-compose.yml (excerpt)
version: "3.9"
services:
  loanrisk_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: loanrisk
      POSTGRES_USER: mifos
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
